"""Build docs/coverage-matrix.md from the upstream catalog snapshots and soc_bridge.coverage.

Usage: python scripts/build_coverage_matrix.py [--check]
--check exits 1 when the committed matrix differs from what the snapshots produce.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from soc_bridge import coverage  # noqa: E402
from soc_bridge.transports import ALERT_VISION_TOOLS, QRADAR_READ_TOOLS  # noqa: E402


def cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def build() -> str:
    qr = json.loads((ROOT / "docs/coverage/qradar-mcp-tools.json").read_text(encoding="utf-8"))
    tv = json.loads((ROOT / "docs/coverage/vision-one-mcp-tools.json").read_text(encoding="utf-8"))
    header = ("| Tool | MCP | Category | Operation | Bridge support | Entry point | Trigger | Limits | Pagination | "
              "Exclusion justification |\n|---|---|---|---|---|---|---|---|---|---|")
    q_rows, t_rows = [], []
    for tool in qr["tools"]:
        name = tool["name"]
        nature = coverage.nature_qradar(tool)
        if name in QRADAR_READ_TOOLS:
            category, entry, trigger, limits = coverage.QRADAR[name]
            q_rows.append([name, "QRadar", category, nature, "integrated", entry, trigger, limits,
                           coverage.pagination_qradar(tool), ""])
        else:
            why = "mutation: blocked (never allowlisted)" if nature.startswith("mutation") else \
                coverage.exclusion(name, coverage.QRADAR_RULES)
            q_rows.append([name, "QRadar", tool["group"], nature, "not integrated", "", "", "",
                           coverage.pagination_qradar(tool), why])
    for tool in tv["tools"]:
        name = tool["name"]
        nature = "read" if tool["registered_as"] == "read" else "write (registered only without -readonly)"
        if name in ALERT_VISION_TOOLS:
            category, entry, trigger, limits = coverage.TREND[name]
            t_rows.append([name, "Vision One", category, nature, "integrated", entry, trigger, limits,
                           coverage.pagination_trend(tool), ""])
        else:
            why = "write tool: not registered in -readonly=true mode and never allowlisted" \
                if tool["registered_as"] == "write" else coverage.exclusion(name, coverage.TREND_RULES)
            t_rows.append([name, "Vision One", tool["toolset"], nature, "not integrated", "", "", "",
                           coverage.pagination_trend(tool), why])
    q_int = sum(r[4] == "integrated" for r in q_rows)
    t_int = sum(r[4] == "integrated" for r in t_rows)
    t_read = sum(t["registered_as"] == "read" for t in tv["tools"])
    q_get = sum(t["verb"] == "GET" for t in qr["tools"])
    lines = [
        "# Upstream MCP coverage matrix",
        "",
        "Generated by `scripts/build_coverage_matrix.py` from the handler snapshots in `docs/coverage/`. Do not edit by hand.",
        "",
        f"- IBM QRadar MCP: {qr['source']['repository']} at `{qr['source']['commit']}` ({qr['source']['commit_date']}): "
        f"{len(qr['tools'])} tools, {q_get} HTTP GET; **{q_int} integrated** (GET reads plus Ariel validation/search creation).",
        f"- Trend Vision One MCP: {tv['source']['repository']} at `{tv['source']['commit']}` ({tv['source']['commit_date']}): "
        f"{len(tv['tools'])} tools, {t_read} registered as read; **{t_int} integrated**.",
        "- A tool in a catalog may be absent from a given installation (feature toggles, toolsets, license, permissions). "
        "The bridge checks availability at run time and reports `tool_absent` separately from an empty result.",
        "- Integrated tools run only when their trigger applies (entity, hypothesis, evidence already collected). "
        "No investigation calls every tool.",
        "- Pagination is what the official handler forwards, not what its schema or README announces.",
        "",
        "## QRadar", "", header]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in q_rows]
    lines += ["", "## Trend Vision One", "", header]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in t_rows]
    return "\n".join(lines) + "\n"


def main() -> int:
    target = ROOT / "docs" / "coverage-matrix.md"
    text = build()
    if "--check" in sys.argv:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            print("docs/coverage-matrix.md is out of date; run scripts/build_coverage_matrix.py", file=sys.stderr)
            return 1
        print("coverage matrix up to date")
        return 0
    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
